# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: weekly
      open-pull-requests-limit: 5
      target-branch: main
      ignore:
        - dependency-name: "*"
      allow:
        - dependency-name: "PrivacyDashboard"
      commit-message:
        prefix: "chore(deps)"
      labels:
        - dependencies
      auto-merge: false
